### ISSUE TITLE
【自荐】Novel-Cloud，SpringCloudAlibaba微服务技术栈学习型项目

### ISSUE THREAD

**Issue by 201206030** [521xueweihan/HelloGitHub#1481]
## 项目推荐
- 项目地址：https://github.com/201206030/novel-cloud

- 类别：Java

- 项目后续更新计划：业余时间更新，紧跟技术潮流。

- 项目描述：
 Novel-Cloud是基于小说精品屋-plus构建的Spring Cloud 微服务技术栈学习型小说项目，致力于原创文学阅读与写作，提供了爬虫工具用于开发过程中测试数据的采集。采用了时下最新的Spring Boot 2.2.5.RELEASE 、Spring Cloud Hoxton.SR4、 MyBatis3DynamicSql、Sharding-Jdbc、Redis、RabbitMq、Elasticsearch、Docker等流行技术，集成了Nacos注册中心/配置中心、Spring Cloud Gateway网关、Spring Boot Admin监控中心、ELK分布式日志分析等基础服务。

- 推荐理由：微服务入门级项目，项目式学习SprngCloudAlibaba微服务技术栈。

- 示例代码：

```
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 47.106.243.172:8848
        namespace: 3960c71a-62ac-4b8f-8c30-bba8e8143a0c
    gateway:
      routes:
        - id: user-route
          uri: lb://user-service 
          predicates:
            - Path=/api/user/** 
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment} 
        - id: monitor-route
          uri: lb://novel-monitor  
          predicates:
            - Path=/monitor/**  
          filters:
            - RewritePath=/monitor/(?<segment>.*), /$\{segment}
```

- 截图：
![QQ20200520-215756](https://s3.ax1x.com/2020/11/11/Bvt3kD.png)
![QQ20200520-215756](https://s3.ax1x.com/2020/11/11/BvtUXt.png)
![QQ20200520-215756](https://s3.ax1x.com/2020/11/11/BvtYpd.png)
![QQ20200520-215756](https://s3.ax1x.com/2020/11/11/Bvtrtg.png)
![QQ20200520-215756](https://s3.ax1x.com/2020/11/11/Bvt2Xq.png)
![QQ20200520-215756](https://s3.ax1x.com/2020/11/11/BvtjHK.png)
![QQ20200520-215756](https://s3.ax1x.com/2020/11/11/BvN99H.png)
![QQ20200520-215756](https://s3.ax1x.com/2020/11/11/BvNkut.png)
![QQ20200520-215756](https://s3.ax1x.com/2020/11/11/BvNK3j.png)
![QQ20200520-215756](https://s3.ax1x.com/2020/11/11/BvNUC4.md.png)
![QQ20200520-215756](https://s3.ax1x.com/2020/11/11/BvNd29.md.png)
