### ISSUE TITLE
自荐开源项目：issues-translate-action

### ISSUE THREAD

**Issue by tomsun28** [521xueweihan/HelloGitHub#1626]
## 项目推荐
- 项目地址：https://github.com/marketplace/actions/issues-translator    
                     https://github.com/tomsun28/issues-translate-action

- 类别：TypeScript  

- 项目后续更新计划：支持自定义翻译issue头，支持自定义翻译目标语言   

- 项目描述：
  - 必写：这是一个使用github action制作的自动识别翻译非英文issue内容的机器人项目。
  - 可选：适用于需要自动识别翻译看不懂的外文issue的场景、能够让初学者学到github action的制作使用流程

- 推荐理由：使用github action作为机器人，不需要格外服务器，能自动识别翻译看不懂的外文issue的场景

- 示例代码：

````
name: 'issue-translator'
on: 
  issue_comment: 
    types: [created]
  issues: 
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: tomsun28/issues-translate-action@v2.3
````

- 截图：   
![效果](https://raw.githubusercontent.com/tomsun28/issues-translate-action/main/dist/bot-demo.png)
