### ISSUE TITLE
项目自荐 | 基于标记语言的开源爬虫框架(Trico cloud云原生)

### ISSUE THREAD

**Issue by shenruisi** [521xueweihan/HelloGitHub#1744]
## 项目推荐
- 项目地址：https://github.com/taofen8/salyut

- 官网地址：https://trico.cloud
- 基本语法: https://www.trico.cloud/doc/

- 类别：Java

- 项目后续更新计划：
   -  提供更多的功能性token。
   - Trico脚本市场。

- 项目描述：
  - 编写自定义的脚本，上传至Trico，Trico将会帮助你部署你的代码，并且以最优的调度原则将任务投递到Trico的爬虫集群。接下来您只需要等待Trico回调你的服务，获取爬取结果。当然您也可以选择将数据投递到你的邮箱，一切都是如此的简单。
 
  - 如果你只希望快速的获取数据，来帮助你的应用尽快的上线，Trico非常适合承担这部分工作。此外Trico脚本的设计基于标记语言，只要你有一些web的知识和了解编程的基本概念就可以快速的写出Trico脚本。

- 推荐理由：
   - 云端部署，无需负担任何机器成本，快速的推进业务。
   - 国内外主节点全覆盖，动态调度。
   - 开放脚本社区，构建数据生态。
   - 遵循Robts协议和用户隐私，安全绿色的获取公开信息。

- 示例代码：
```yaml
- segment: #This is a trico script sample. A web calculator.
    name: 'calc'
    args: {0: '/input'}
    body:
    - load: '"http://www.baidu.com"' #load page of Baidu
    - wait: {ele: '#su', type: 'presence'} #wait element appear
    - fill: {ele: '#kw', value: '$/input'}
    - click: {ele: '#su'} #click search button
    - wait: {ele: '.op_new_val_screen_result', type: 'presence'} #fetch the result
    - select: {ele: '.op_new_val_screen_result', path: '/result'}
    - put: { path: '/resultInt', value: '$/result', lambda: 'x -> return parseInt(x)'}
    - return: '$/resultInt'
- callin: {seg: '"calc"', 0: '"1+1"'} #call the segment named 'calc' and pass the argument '1+1'
- return: '$1'
```
