### ISSUE TITLE
【开源项目】云原生集群内访问集群外部服务场景使用固定的endpoint维护增加探活功能

### ISSUE THREAD

**Issue by cuisongliu** [521xueweihan/HelloGitHub#2091]
## 项目推荐
- 项目地址：[endpoints-operator](https://github.com/sealyun/endpoints-operator)

- 类别： GO

- 项目后续更新计划：新增k8s webhook校验等

- 项目描述：endpoints-operator是一个云原生、高可靠性、高性能、面向K8s内部服务访问外部服务的具备探活功能的4层LB。
  
- 推荐理由：
   - 完全使用K8s原生的Service、Endpoint资源，无自定义IPVS策略，依托K8s的Service能力，高可靠。
   - 通过controller管理一个CRD资源ClusterEndpoint（缩写cep）即可，无需手动管理Service和Endpoint两个资源
   - 完全兼容已有的自定义Service、Endpoint资源，可无缝切换至endpoints-operator管理。
   - 原生的IPVS 4层负载，未引入Nginx、HAProxy等LB，降低了复杂度，满足高性能和高稳定性的需求
   - 支持http,tcp,udp,grpc等探活

- 示例代码：
   安装：
   ```
    git clone https://github.com/sealyun/endpoints-operator.git
    cd endpoints-operator 
    checkout v0.1.0
    helm install -n kube-system endpoints-operator config/charts/endpoints-operator
   ```
   使用：
   ```
   apiVersion: sealyun.com/v1beta1
  kind: ClusterEndpoint
  metadata:
    name: wordpress
    namespace: default
  spec:
    hosts:
      - 172.18.191.215
    periodSeconds: 10
    ports:
      - name: wp-https
        protocol: TCP
        port: 38081
        targetPort: 443
        tcpSocket:
          enable: true
        timeoutSeconds: 1
        failureThreshold: 3
        successThreshold: 1
      - name: wp-http
        protocol: TCP
        port: 38082
        targetPort: 80
        httpGet:
          path: /healthz
          scheme: http
        timeoutSeconds: 1
        failureThreshold: 3
        successThreshold: 1      
      - name: wp-udp
        protocol: UDP
        port: 38003
        targetPort: 1234
        udpSocket:
          enable: true
          data: "This is flag data for UDP svc test"
        timeoutSeconds: 1
        failureThreshold: 3
        successThreshold: 1
      - name: wp-grpc
        protocol: TCP
        port: 38083
        targetPort: 8080
        grpc:
          enable: true
        timeoutSeconds: 1
        failureThreshold: 3
        successThreshold: 1
   ```
