### ISSUE TITLE
生成Git ChangeLog的工具，包含在GitLab CI/CD中生成并推送Release工作流以及GitHub Action的推送Release工作流

### ISSUE THREAD

**Issue by shencangsheng** [521xueweihan/HelloGitHub#2132]
## 项目推荐
- 项目地址：[Git-Release-Workflow](https://github.com/shencangsheng/Git-Release-Workflow)

- 类别：请从中选择（其他）

- 项目后续更新计划：

- 项目描述：
  - 必写：适用于私有GitLab在企业内部使用CI/CD生成个性化的Release。
  - 可选：GitLab CI/CD；GitHub Action初学者快速学习。
  - 描述长度（不包含示例代码）: 生成Git ChangeLog的工具，包含在GitLab CI/CD中生成并推送Release工作流以及GitHub Action的推送Release工作流

- 推荐理由：清晰易懂的脚本和示例，可快速学习Git相关工作流的使用。

- 示例代码：
```yml
release:
  rules:
    - if: '$CI_COMMIT_TAG != null && $CI_PIPELINE_SOURCE == "push"'
      when: on_success
  stage: release-note
  image: shencangsheng/gitlab-pipeline-release:latest
  script:
    # 注意区分GitLab版本
    # <= 13.x 使用 post-gitlab-release-13x
    # >= 14.x 使用 post-gitlab-release-14x
    - post-gitlab-release-14x
```

- 截图：
![image](https://user-images.githubusercontent.com/67856731/159208242-74c90092-eda9-4233-a751-4100f9818414.png)

## 提示（提交时请删除以下内容）
> 点击上方 “Preview” 更方便地阅读以下内容，

提高项目收录的概率方法如下：
1. 到 HelloGitHub 网站首页：https://hellogithub.com 搜索要推荐的项目地址，查看准备推荐的项目是否被推荐过。

2. 根据 [项目审核标准说明](https://github.com/521xueweihan/HelloGitHub/issues/271) 修改项目

3. 如您推荐的项目收录到《HelloGitHub》月刊，您的 GitHub 帐号将展示在 [贡献人列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)，**同时会在本 issues 中通知您**。

再次感谢您对 HelloGitHub 项目的支持！
