### ISSUE TITLE
【开源自荐】C/C++ 代码格式化和静态分析检查的一站式工作流 Cpp Linter

### ISSUE THREAD

**Issue by shenxianpeng** [521xueweihan/HelloGitHub#2530]
## 推荐项目

- 项目地址：https://github.com/cpp-linter/cpp-linter-action

- 类别：C、C++

- 项目标题：Cpp Linter - C/C++ 代码格式化和静态分析检查的一站式工作流

- 项目描述：使用 `clang-format` 和 `clang-tidy` 来检查 C/C++ 代码格式化和静态分析检查，将检查结果通过 GitHub 评论或注释进行展示。

- 亮点：[cpp-linter](https://github.com/cpp-linter) 组织既提供了 [GitHub Action](https://github.com/cpp-linter/cpp-linter-action)，提供了 [pre-commit hook](https://github.com/cpp-linter/cpp-linter-hooks)，解决不同场景的需求。

- 示例代码：

    ```yaml
    name: cpp-linter
    
    on: pull_request
    
    jobs:
      cpp-linter:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - uses: cpp-linter/cpp-linter-action@v2
            id: linter
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            with:
              style: file
    
          - name: Fail fast?!
            if: steps.linter.outputs.checks-failed > 0
            run: echo "Some files failed the linting checks!"
            # for actual deployment
            # run: exit 1
    ```

- 截图：

  ![image](https://user-images.githubusercontent.com/3353385/231986201-3ad75e8f-855f-4300-a10f-efd0f06711d5.png)

  ![image](https://user-images.githubusercontent.com/3353385/231986237-364f6f9e-d09a-44bd-9f19-f05ea34e5439.png)
